const fs = require('fs');

const translationsStr = {
  es: {
    collector: "Cobrador:",
    period: "Periodo:",
    all: "TODOS",
    totalAudited: "Total Cartera Auditada:",
    clientsWithBalance: "Clientes con Saldo",
    outOfRange: "FUERA DE RANGO",
    days: "Días",
    controlTitle: "Control de Gestión y Morosidad (Prioridad S/ REGISTRO):",
    client: "CLIENTE",
    balance: "SALDO",
    overdue: "ATRASO",
    unregistered: "S/ REGIST.",
    lastPayment: "ÚLT. PAGO",
    status: "ESTADO",
    location: "UBICACION",
    critical: "CRÍTICO",
    alert: "ALERTA",
    attention: "ATENCIÓN",
    normal: "NORMAL",
    d: "d.",
    locNr: "UBICACION NR",
    locR: "UBICACION R",
    never: "NUNCA",
    docGenerated: "DOCUMENTO GENERADO POR SISTEMA DE AUDITORIA"
  },
  en: {
    collector: "Collector:",
    period: "Period:",
    all: "ALL",
    totalAudited: "Total Audited Portfolio:",
    clientsWithBalance: "Clients with Balance",
    outOfRange: "OUT OF RANGE",
    days: "Days",
    controlTitle: "Management and Delinquency Control (Priority UNREGISTERED):",
    client: "CLIENT",
    balance: "BALANCE",
    overdue: "OVERDUE",
    unregistered: "UNREGIST.",
    lastPayment: "LAST PAY.",
    status: "STATUS",
    location: "LOCATION",
    critical: "CRITICAL",
    alert: "ALERT",
    attention: "ATTENTION",
    normal: "NORMAL",
    d: "d.",
    locNr: "LOCATION NR",
    locR: "LOCATION R",
    never: "NEVER",
    docGenerated: "DOCUMENT GENERATED BY AUDIT SYSTEM"
  },
  pt: {
    collector: "Cobrador:",
    period: "Período:",
    all: "TODOS",
    totalAudited: "Total Carteira Auditada:",
    clientsWithBalance: "Clientes com Saldo",
    outOfRange: "FORA DE ALCANCE",
    days: "Dias",
    controlTitle: "Controle de Gestão e Inadimplência (Prioridade S/ REGISTRO):",
    client: "CLIENTE",
    balance: "SALDO",
    overdue: "ATRASO",
    unregistered: "S/ REGIST.",
    lastPayment: "ÚLT. PAG.",
    status: "STATUS",
    location: "LOCALIZAÇÃO",
    critical: "CRÍTICO",
    alert: "ALERTA",
    attention: "ATENÇÃO",
    normal: "NORMAL",
    d: "d.",
    locNr: "LOCALIZAÇÃO NR",
    locR: "LOCALIZAÇÃO R",
    never: "NUNCA",
    docGenerated: "DOCUMENTO GERADO PELO SISTEMA DE AUDITORIA"
  },
  fr: {
    collector: "Recouvreur :",
    period: "Période :",
    all: "TOUS",
    totalAudited: "Portefeuille Total Audité :",
    clientsWithBalance: "Clients avec Solde",
    outOfRange: "HORS DE PORTÉE",
    days: "Jours",
    controlTitle: "Contrôle de Gestion et Impayés (Priorité SANS REGISTRE) :",
    client: "CLIENT",
    balance: "SOLDE",
    overdue: "RETARD",
    unregistered: "SANS REG.",
    lastPayment: "DERN. PAIE.",
    status: "STATUT",
    location: "EMPLACEMENT",
    critical: "CRITIQUE",
    alert: "ALERTE",
    attention: "ATTENTION",
    normal: "NORMAL",
    d: "j.",
    locNr: "EMPLACEMENT NR",
    locR: "EMPLACEMENT R",
    never: "JAMAIS",
    docGenerated: "DOCUMENT GÉNÉRÉ PAR SYSTÈME D'AUDIT"
  }
};

let content = fs.readFileSync('utils/translations.ts', 'utf8');

const langs = ['es', 'en', 'pt', 'fr'];
for (const lang of langs) {
  const langIndex = content.indexOf(`  ${lang}: {`);
  if (langIndex !== -1) {
    const settingsPageIndex = content.indexOf(`    settingsPage: {`, langIndex);
    if (settingsPageIndex !== -1) {
      let auditBlock = `    auditPdf: {\n`;
      for (const [k, v] of Object.entries(translationsStr[lang])) {
        auditBlock += `      ${k}: "${v}",\n`;
      }
      auditBlock += `    },\n`;
      content = content.slice(0, settingsPageIndex) + auditBlock + content.slice(settingsPageIndex);
    }
  }
}
fs.writeFileSync('utils/translations.ts', content, 'utf8');

// Update Reports.tsx
let reports = fs.readFileSync('components/Reports.tsx', 'utf8');

reports = reports.replace(
  /\`Cobrador: \$\{selectedCollectorData \? selectedCollectorData\.name\.toUpperCase\(\) : 'TODOS'\}\`/g,
  "`${t.auditPdf?.collector || 'Cobrador:'} ${selectedCollectorData ? selectedCollectorData.name.toUpperCase() : (t.auditPdf?.all || 'TODOS')}`"
);

reports = reports.replace(
  /\`Periodo: \$\{startDate\} \/ \$\{endDate\}\`/g,
  "`${t.auditPdf?.period || 'Periodo:'} ${startDate} / ${endDate}`"
);

reports = reports.replace(
  /\`Total Cartera Auditada: \$\{auditData\.length\} Clientes con Saldo\`/g,
  "`${t.auditPdf?.totalAudited || 'Total Cartera Auditada:'} ${auditData.length} ${t.auditPdf?.clientsWithBalance || 'Clientes con Saldo'}`"
);

reports = reports.replace(
  /\`FUERA DE RANGO \(\>\=4 D.as\): \$\{alertasCount\}\`/g,
  "`${t.auditPdf?.outOfRange || 'FUERA DE RANGO'} (>=4 ${t.auditPdf?.days || 'Días'}): ${alertasCount}`"
);

reports = reports.replace(
  /doc\.text\('Control de Gesti.n y Morosidad \(Prioridad S\/ REGISTRO\):', 20, 105\);/g,
  "doc.text(t.auditPdf?.controlTitle || 'Control de Gestión y Morosidad (Prioridad S/ REGISTRO):', 20, 105);"
);

// Table headers
reports = reports.replace(/doc\.text\('CLIENTE', 26, currentY\);/g, "doc.text(t.auditPdf?.client || 'CLIENTE', 26, currentY);");
reports = reports.replace(/doc\.text\('SALDO', 72, currentY\);/g, "doc.text(t.auditPdf?.balance || 'SALDO', 72, currentY);");
reports = reports.replace(/doc\.text\('ATRASO', 95, currentY\);/g, "doc.text(t.auditPdf?.overdue || 'ATRASO', 95, currentY);");
reports = reports.replace(/doc\.text\('S\/ REGIST\.', 114, currentY\);/g, "doc.text(t.auditPdf?.unregistered || 'S/ REGIST.', 114, currentY);");
reports = reports.replace(/doc\.text\('.sLT\. PAGO', 136, currentY\);/g, "doc.text(t.auditPdf?.lastPayment || 'ÚLT. PAGO', 136, currentY);");
reports = reports.replace(/doc\.text\('ESTADO', 160, currentY\);/g, "doc.text(t.auditPdf?.status || 'ESTADO', 160, currentY);");
reports = reports.replace(/doc\.text\('UBICACION', 176, currentY\);/g, "doc.text(t.auditPdf?.location || 'UBICACION', 176, currentY);");

// Days abbr "d."
reports = reports.replace(/\`\$\{item\.atraso\} d\.\`/g, "`\${item.atraso} ${t.auditPdf?.d || 'd.'}`");
reports = reports.replace(/\`\$\{item\.diasInactivo \> 365 \? '---' : item\.diasInactivo \+ ' d\.'\}\`/g, "`${item.diasInactivo > 365 ? '---' : item.diasInactivo + ' ' + (t.auditPdf?.d || 'd.')}`");
reports = reports.replace(/\`\$\{item\.lastPaymentDays\} d\.\`/g, "`\${item.lastPaymentDays} ${t.auditPdf?.d || 'd.'}`");

// NUNCA
reports = reports.replace(/doc\.text\('NUNCA', 136, currentY\);/g, "doc.text(t.auditPdf?.never || 'NUNCA', 136, currentY);");

// Location 
reports = reports.replace(/doc\.text\('UBICACION NR', 176, currentY\);/g, "doc.text(t.auditPdf?.locNr || 'UBICACION NR', 176, currentY);");
reports = reports.replace(/doc\.text\('UBICACION R', 176, currentY\);/g, "doc.text(t.auditPdf?.locR || 'UBICACION R', 176, currentY);");

// Status variables
reports = reports.replace(/let gapStatus = 'NORMAL';/g, "let gapStatus = t.auditPdf?.normal || 'NORMAL';");
reports = reports.replace(/gapStatus = 'CR.TICO';/g, "gapStatus = t.auditPdf?.critical || 'CRÍTICO';");
reports = reports.replace(/gapStatus = 'ALERTA';/g, "gapStatus = t.auditPdf?.alert || 'ALERTA';");
reports = reports.replace(/gapStatus = 'ATENCI.N';/g, "gapStatus = t.auditPdf?.attention || 'ATENCIÓN';");

reports = reports.replace(/item\.gapStatus === 'CR.TICO'/g, "item.gapStatus === (t.auditPdf?.critical || 'CRÍTICO')");
reports = reports.replace(/item\.gapStatus === 'ALERTA'/g, "item.gapStatus === (t.auditPdf?.alert || 'ALERTA')");
reports = reports.replace(/item\.gapStatus === 'ATENCI.N'/g, "item.gapStatus === (t.auditPdf?.attention || 'ATENCIÓN')");

reports = reports.replace(/doc\.text\('DOCUMENTO GENERADO POR SISTEMA DE AUDITORIA', 105, 290, \{ align: 'center' \}\);/g, "doc.text(t.auditPdf?.docGenerated || 'DOCUMENTO GENERADO POR SISTEMA DE AUDITORIA', 105, 290, { align: 'center' });");

fs.writeFileSync('components/Reports.tsx', reports, 'utf8');
console.log('PDF translation complete.');
