const fs = require('fs');

let content = fs.readFileSync('utils/translations.ts', 'utf8');

const newTexts = {
  es: {
    commission: {
      allConsolidated: 'TODOS (CONSOLIDADO)',
      expensePlaceholder: 'Observación'
    },
    receiptImage: {
      visitNotification: 'NOTIFICACIÓN DE VISITA (MORA)',
      officialReceipt: 'COMPROBANTE OFICIAL DE PAGO',
      clientTitular: 'CLIENTE / TITULAR',
      date: 'FECHA',
      time: 'HORA',
      statusRegistered: 'ESTADO REGISTRADO',
      noPaymentToday: 'SIN ABONO HOY',
      paymentRegistered: 'PAGO REGISTRADO',
      pleaseContactAdmin: 'FAVOR COMUNICARSE CON ADMINISTRACIÓN',
      thanksForPunctuality: '¡GRACIAS POR SU PUNTUALIDAD!',
      remainingBalance: 'SALDO RESTANTE:',
      daysOverdue: 'DÍAS EN MORA:',
      days: 'días',
      installmentsPaid: 'CUOTAS PAGADAS:',
      avoidNegativeReport: 'EVITE EL REPORTE NEGATIVO EN CENTRALES DE RIESGO.',
      autoGenerated: 'DOCUMENTO GENERADO POR SISTEMA AUTOMATIZADO',
      reportId: 'REPORTE'
    },
    confirmations: {
      deletePaymentDefinitive: '¿BORRAR ESTE PAGO DEFINITIVAMENTE? SE REVERTIRÁN LOS SALDOS.'
    }
  },
  en: {
    commission: {
      allConsolidated: 'ALL (CONSOLIDATED)',
      expensePlaceholder: 'Observation'
    },
    receiptImage: {
      visitNotification: 'VISIT NOTIFICATION (OVERDUE)',
      officialReceipt: 'OFFICIAL PAYMENT RECEIPT',
      clientTitular: 'CLIENT / HOLDER',
      date: 'DATE',
      time: 'TIME',
      statusRegistered: 'REGISTERED STATUS',
      noPaymentToday: 'NO PAYMENT TODAY',
      paymentRegistered: 'PAYMENT REGISTERED',
      pleaseContactAdmin: 'PLEASE CONTACT ADMINISTRATION',
      thanksForPunctuality: 'THANK YOU FOR YOUR PUNCTUALITY!',
      remainingBalance: 'REMAINING BALANCE:',
      daysOverdue: 'DAYS OVERDUE:',
      days: 'days',
      installmentsPaid: 'INSTALLMENTS PAID:',
      avoidNegativeReport: 'AVOID NEGATIVE REPORTING IN CREDIT BUREAUS.',
      autoGenerated: 'DOCUMENT GENERATED BY AUTOMATED SYSTEM',
      reportId: 'REPORT'
    },
    confirmations: {
      deletePaymentDefinitive: 'DELETE THIS PAYMENT PERMANENTLY? BALANCES WILL BE REVERTED.'
    }
  },
  pt: {
    commission: {
      allConsolidated: 'TODOS (CONSOLIDADO)',
      expensePlaceholder: 'Observação'
    },
    receiptImage: {
      visitNotification: 'NOTIFICAÇÃO DE VISITA (ATRASO)',
      officialReceipt: 'COMPROVANTE OFICIAL DE PAGAMENTO',
      clientTitular: 'CLIENTE / TITULAR',
      date: 'DATA',
      time: 'HORA',
      statusRegistered: 'STATUS REGISTRADO',
      noPaymentToday: 'SEM PAGAMENTO HOJE',
      paymentRegistered: 'PAGAMENTO REGISTRADO',
      pleaseContactAdmin: 'FAVOR ENTRAR EM CONTATO COM A ADMINISTRAÇÃO',
      thanksForPunctuality: 'OBRIGADO PELA SUA PONTUALIDADE!',
      remainingBalance: 'SALDO RESTANTE:',
      daysOverdue: 'DIAS EM ATRASO:',
      days: 'dias',
      installmentsPaid: 'PARCELAS PAGAS:',
      avoidNegativeReport: 'EVITE RELATÓRIOS NEGATIVOS NOS ÓRGÃOS DE CRÉDITO.',
      autoGenerated: 'DOCUMENTO GERADO POR SISTEMA AUTOMATIZADO',
      reportId: 'RELATÓRIO'
    },
    confirmations: {
      deletePaymentDefinitive: 'EXCLUIR ESTE PAGAMENTO DEFINITIVAMENTE? OS SALDOS SERÃO REVERTIDOS.'
    }
  },
  fr: {
    commission: {
      allConsolidated: 'TOUS (CONSOLIDÉ)',
      expensePlaceholder: 'Observation'
    },
    receiptImage: {
      visitNotification: 'NOTIFICATION DE VISITE (RETARD)',
      officialReceipt: 'REÇU OFFICIEL DE PAIEMENT',
      clientTitular: 'CLIENT / TITULAIRE',
      date: 'DATE',
      time: 'HEURE',
      statusRegistered: 'STATUT ENREGISTRÉ',
      noPaymentToday: 'AUCUN PAIEMENT AUJOURD\'HUI',
      paymentRegistered: 'PAIEMENT ENREGISTRÉ',
      pleaseContactAdmin: 'VEUILLEZ CONTACTER L\'ADMINISTRATION',
      thanksForPunctuality: 'MERCI POUR VOTRE PONCTUALITÉ !',
      remainingBalance: 'SOLDE RESTANT :',
      daysOverdue: 'JOURS DE RETARD :',
      days: 'jours',
      installmentsPaid: 'MENSUALITÉS PAYÉES :',
      avoidNegativeReport: 'ÉVITEZ LES RAPPORTS NÉGATIFS DANS LES BUREAUX DE CRÉDIT.',
      autoGenerated: 'DOCUMENT GÉNÉRÉ PAR SYSTÈME AUTOMATISÉ',
      reportId: 'RAPPORT'
    },
    confirmations: {
      deletePaymentDefinitive: 'SUPPRIMER CE PAIEMENT DÉFINITIVEMENT ? LES SOLDES SERONT RÉTABLIS.'
    }
  }
};

for (const lang of ['es', 'en', 'pt', 'fr']) {
  // Update commission block
  let langIndex = content.indexOf(`  ${lang}: {`);
  if (langIndex !== -1) {
    const commissionIndex = content.indexOf(`    commission: {`, langIndex);
    if (commissionIndex !== -1) {
      const historyIndex = content.indexOf(`history:`, commissionIndex);
      if (historyIndex !== -1) {
        const nextLineIndex = content.indexOf(`\n`, historyIndex);
        content = content.slice(0, nextLineIndex) + `,\n        allConsolidated: '${newTexts[lang].commission.allConsolidated}',\n        expensePlaceholder: '${newTexts[lang].commission.expensePlaceholder}'` + content.slice(nextLineIndex);
      }
    }
    
    // Add receiptImage and confirmations at the end of the lang block before the next lang block
    // We can just append it before `settingsPage:` block or at the end of `lang` block
    const settingsPageIndex = content.indexOf(`    settingsPage: {`, langIndex);
    if (settingsPageIndex !== -1) {
      const receiptStr = `\n    receiptImage: {\n` + Object.entries(newTexts[lang].receiptImage).map(([k, v]) => `      ${k}: "${v.replace(/"/g, '\\"')}"`).join(',\n') + `\n    },\n`;
      const confirmationsStr = `    confirmations: {\n      deletePaymentDefinitive: "${newTexts[lang].confirmations.deletePaymentDefinitive.replace(/"/g, '\\"')}"\n    },\n`;
      
      content = content.slice(0, settingsPageIndex) + receiptStr + confirmationsStr + content.slice(settingsPageIndex);
    }
  }
}

fs.writeFileSync('utils/translations.ts', content, 'utf8');

// Update CollectorCommission.tsx
let collectorContent = fs.readFileSync('components/CollectorCommission.tsx', 'utf8');

// Replace UI text
collectorContent = collectorContent.replace(
  />TODOS \(CONSOLIDADO\)</g,
  '>{t.commission?.allConsolidated || "TODOS (CONSOLIDADO)"}<'
);
collectorContent = collectorContent.replace(
  /placeholder="Observacion"/g,
  'placeholder={t.commission?.expensePlaceholder || "Observacion"}'
);
collectorContent = collectorContent.replace(
  /confirm\('¿BORRAR ESTE PAGO DEFINITIVAMENTE\? SE REVERTIRÁN LOS SALDOS\.'\)/g,
  'confirm(t.confirmations?.deletePaymentDefinitive || "¿BORRAR ESTE PAGO DEFINITIVAMENTE? SE REVERTIRÁN LOS SALDOS.")'
);

// Replace Receipt texts
collectorContent = collectorContent.replace(
  /isNoPay \? 'NOTIFICACI.N DE VISITA \(MORA\)' : 'COMPROBANTE OFICIAL DE PAGO'/g,
  "isNoPay ? (t.receiptImage?.visitNotification || 'NOTIFICACIÓN DE VISITA (MORA)') : (t.receiptImage?.officialReceipt || 'COMPROBANTE OFICIAL DE PAGO')"
);
collectorContent = collectorContent.replace(
  /CLIENTE \/ TITULAR/g,
  "{t.receiptImage?.clientTitular || 'CLIENTE / TITULAR'}"
);
collectorContent = collectorContent.replace(
  />FECHA</g,
  ">{t.receiptImage?.date || 'FECHA'}<"
);
collectorContent = collectorContent.replace(
  />HORA</g,
  ">{t.receiptImage?.time || 'HORA'}<"
);
collectorContent = collectorContent.replace(
  /ESTADO REGISTRADO/g,
  "{t.receiptImage?.statusRegistered || 'ESTADO REGISTRADO'}"
);
collectorContent = collectorContent.replace(
  /isNoPay \? 'SIN ABONO HOY' : 'PAGO REGISTRADO'/g,
  "isNoPay ? (t.receiptImage?.noPaymentToday || 'SIN ABONO HOY') : (t.receiptImage?.paymentRegistered || 'PAGO REGISTRADO')"
);
collectorContent = collectorContent.replace(
  /isNoPay \? 'FAVOR COMUNICARSE CON ADMINISTRACI.N' : '¡GRACIAS POR SU PUNTUALIDAD!'/g,
  "isNoPay ? (t.receiptImage?.pleaseContactAdmin || 'FAVOR COMUNICARSE CON ADMINISTRACIÓN') : (t.receiptImage?.thanksForPunctuality || '¡GRACIAS POR SU PUNTUALIDAD!')"
);
collectorContent = collectorContent.replace(
  /SALDO RESTANTE:/g,
  "{t.receiptImage?.remainingBalance || 'SALDO RESTANTE:'}"
);
collectorContent = collectorContent.replace(
  /D.AS EN MORA:/g,
  "{t.receiptImage?.daysOverdue || 'DÍAS EN MORA:'}"
);
collectorContent = collectorContent.replace(
  /\{daysOverdue\} d.as/g,
  "{daysOverdue} {t.receiptImage?.days || 'días'}"
);
collectorContent = collectorContent.replace(
  /CUOTAS PAGADAS:/g,
  "{t.receiptImage?.installmentsPaid || 'CUOTAS PAGADAS:'}"
);
collectorContent = collectorContent.replace(
  /EVITE EL REPORTE NEGATIVO EN CENTRALES DE RIESGO./g,
  "{t.receiptImage?.avoidNegativeReport || 'EVITE EL REPORTE NEGATIVO EN CENTRALES DE RIESGO.'}"
);
collectorContent = collectorContent.replace(
  /DOCUMENTO GENERADO POR SISTEMA AUTOMATIZADO/g,
  "{t.receiptImage?.autoGenerated || 'DOCUMENTO GENERADO POR SISTEMA AUTOMATIZADO'}"
);
collectorContent = collectorContent.replace(
  /REPORTE - \{sharingLog\.id\}/g,
  "{t.receiptImage?.reportId || 'REPORTE'} - {sharingLog.id}"
);

fs.writeFileSync('components/CollectorCommission.tsx', collectorContent, 'utf8');
console.log('CollectorCommission texts updated.');
